### ISSUE TITLE
Empty buttons can be initialized in the Simulator

### ISSUE THREAD

**Issue by Nasiff** [Derevi/submission#3]
### Steps to reproduce
In the configurator app, have empty labels and then click on the same label to initialize that 'empty' button. Then when you compile audio and then save the state, the simulator opens up with empty buttons.

### Actual Results
Clicking on these empty buttons crash the simulator with a Null Pointer Exception

### Expected Results
The ConfigurationApp should have an error dialog warning the user that Empty text labels aren't allowed so that the simulator isn't in a state that allows the creation of empty buttons.

### Build Date & Platform
Platform: Windows 10 Home

### Additional Builds and Platforms
The bug is very general and it is expected to cause an issue on all platforms this application runs on.

**Comment by Derevi** [comment]
Issues is fixed. precondition was set to data object, to not allow empty string input, and throws a new error. Will added a dialog box to reflect this in later updates.
