### ISSUE TITLE
Long strings changing save button size

### ISSUE THREAD

**Issue by tonyly98** [Derevi/submission#4]
#### Steps to reproduce:
Open the configuration application and enter a long string such as "TTTTTTTTTTTTTTTTTTTTTTTTTTTTT", click on the string again to save to the button.

#### Actual results:
The steps above results in the bottom save buttons and more to be shifted/squished, making these bottom button unreadable. 

#### Expected result:
The bottom button should have stayed a constant size. Either the created audio button text should be cut so only the first portion is readable, or the button should have just extended.

#### Build date & platform:
Platform: Windows 10

#### Additional Builds and Platforms:
JavaFX version: 11.0.2
Java build: open JDK 11

**Comment by rtam16** [comment]
Structure of the program has been refactored.  Buttons are now a fixed size, and therefore the constant buttons (ie. the save button) will always be seen.
